### ISSUE TITLE
does it respect the runtimeVersion property from app.json ? 

### ISSUE THREAD

**Issue by a-eid** [umbertoghio/self-hosted-expo-updates-server#10]
Great work, thank you 

typically you should not install an update unless it's tuntime compatible, I have not seem any mentions for the runtimeVersion in the code, does it respect it. if not how do you deal with that ?

**Comment by umbertoghio** [comment]
Hi, thank you! 
Yes, runtimeVersion and release channels are in the manifest and respected by the client on the mobile
