### ISSUE TITLE
Crash when applying updates: com.facebook.jni.CppException: Compiling JS failed: 1:1:Invalid UTF-8 lead byte 0x93 Buffer size 875336 starts with: 9397050a8180af03944f0d2400050206 and has protection mode(s): r--p

### ISSUE THREAD

**Issue by a-eid** [umbertoghio/self-hosted-expo-updates-server#11]
when applying the updates, the app crashes with the following error 

FATAL EXCEPTION: mqt_js

com.facebook.jni.CppException: Compiling JS failed: 1:1:Invalid UTF-8 lead byte 0x93 Buffer size 875336 starts with: 9397050a8180af03944f0d2400050206 and has protection mode(s): r--p

FATAL EXCEPTION: mqt_js
Process: com.aeid.testapp1, PID: 13747
com.facebook.jni.CppException: Compiling JS failed: 1:1:Invalid UTF-8 lead byte 0x93 Buffer size 875336 starts with: 9397050a8180af03944f0d2400050206 and has protection mode(s): r--p
	at com.facebook.jni.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:223)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
	at java.lang.Thread.run(Thread.java:923)
	
what could be the issue ?

**Comment by umbertoghio** [comment]
strange, I'll have a look this Saturday

**Comment by a-eid** [comment]
I'm building the app with `eas`, I changed the release channel here to staging. 
![Screenshot 2024-01-03 at 18 23 50](https://github.com/umbertoghio/self-hosted-expo-updates-server/assets/19273413/491eac69-df75-4fad-bd42-d41051967f4f)

where should I be looking, I would like to debug this issue. 

thank you.

**Comment by a-eid** [comment]
I updated the app certificate with the new certificate code, do I need to download the private key and place somewhere ? 


![Screenshot 2024-01-03 at 18 31 06](https://github.com/umbertoghio/self-hosted-expo-updates-server/assets/19273413/8bc4bcf9-71bc-4df0-8bce-47e18cfa3c42)

**Comment by umbertoghio** [comment]
oh, that could indeed be the issue, you need to embed the private key in your application, check the provided example codeSigningCertificate key in app.json
![image](https://github.com/umbertoghio/self-hosted-expo-updates-server/assets/25666241/db401625-47eb-4dc8-87a6-60e7ce4f1813)
