### ISSUE TITLE
`expo-constatns` expoConfig is not working as expected. 

### ISSUE THREAD

**Issue by a-eid** [umbertoghio/self-hosted-expo-updates-server#13]
I'm trying to display the app version via expo-constants but am getting undefined for `Constants.expoConfig.version`

```
import Constants from "expo-constants"

Constants.expoConfig.version // undefined. 
```

**Comment by umbertoghio** [comment]
Seems that the expo-constants has been updated, check the expo version and documentation https://docs.expo.dev/versions/latest/sdk/constants/#manifest

**Comment by a-eid** [comment]
I'm not sure I'm following, I thought `Constants.manifest` is already deprecated. 

<img width="837" alt="Screenshot 2024-02-13 at 4 21 11 PM" src="https://github.com/umbertoghio/self-hosted-expo-updates-server/assets/19273413/9b1f3885-d589-41dc-a725-5b1774882b3f">

also I don't think the manifest has what I'm looking for `version`. I think for such use case it's recommended to use `Constants.expoConfig`

furthermore it does work before publishing an update, after doing so it stops working.

**Comment by umbertoghio** [comment]
you are right! I'll provide an update before Friday
Thanks for pointing it out

**Comment by umbertoghio** [comment]
@a-eid sorry Ahmed but I didn't managed to look at this and I'm leaving for holiday.

Feel free to do a pull request and I'll approve it, alternatively please have some patience, I'll look at this in mid-march

**Comment by a-eid** [comment]
thank you @umbertoghio,  am not sure where to start, but I'll try, 

FYI this is `expoConfig` [getter](https://github.com/expo/expo/blob/334d42c4d13a40dc1c4c30a8d2d8f88a28de9131/packages/expo-constants/src/Constants.ts#L147C3-L147C13) function from `expo-constants`

<img width="839" alt="Screenshot 2024-02-16 at 8 11 50 AM" src="https://github.com/umbertoghio/self-hosted-expo-updates-server/assets/19273413/0ef76ccf-4fea-49e6-bb48-c9ddaec90d7f">


when updating my app, I tried copying over the generated expo config `ExpoConfig.getConfig` to `dist/app.json` but it does not seem to be working.

**Comment by a-eid** [comment]
@umbertoghio I wasn't able to fix this, do you maybe have an update on it ?

**Comment by a-eid** [comment]
when logging the `expoConfig`, I get this output which is not correct, this seem to be the list of assets from `dist/metadata.json`.  any idea what could be causing it ? 


![Screenshot 2024-03-31 at 10 01 09 PM](https://github.com/umbertoghio/self-hosted-expo-updates-server/assets/19273413/fcd07d3b-ea85-445c-ba0b-187135b0043f)

BTW this is after running an update.

**Comment by a-eid** [comment]
@umbertoghio any updates on this, I'm not sure how to fix it TBH.

**Comment by umbertoghio** [comment]
Hello,
sorry, due to additional projects I took I am unable to maintain / assist further on this
