### ISSUE TITLE
`releaseChannel` defaulting to "default" even thou it's defined in eas.json, SDK 50 ? 

### ISSUE THREAD

**Issue by a-eid** [umbertoghio/self-hosted-expo-updates-server#14]

**Comment by umbertoghio** [comment]
I'm in holiday until mid march, I will try this out as soon as I am back

**Comment by a-eid** [comment]
@umbertoghio thank you, I am reporting bugs as I see them, this is probably an expo issue or a project specific issue, I'm looking into it.

**Comment by a-eid** [comment]
I am not sure why but I sometimes get the `releaseChannel` as `default`.

**Comment by a-eid** [comment]
do you have any updates here, were you able to reproduce this. 

also I would like to know how you switch env variables between profile ie: "production" & 'staging" ?  

basically all I'm trying to do is identify which EAS profile used to build the app ( "production" or "staging" ) so I can change my config file.

**Comment by umbertoghio** [comment]
Hello, sorry for the delay, I will look into this as soon as possible

**Comment by a-eid** [comment]
@umbertoghio no worries. 

I would like to know how to identify the profile used to build the app, ie: I need to know which build I am running staging or production. how do you achieve that ?

**Comment by a-eid** [comment]
I found that this is an expo related bug, to get around it we have to define extra headers in `app.config.ts` `updates` object like so. 


![Screenshot 2024-04-13 at 1 19 08 PM](https://github.com/umbertoghio/self-hosted-expo-updates-server/assets/19273413/b2d87010-c64b-449d-9bbf-6c331b73364c)

**Comment by a-eid** [comment]
I think this is an acceptable solution. 

```json
"reuestHeaders": {
  "release-channel": "channel"
}
```
