### ISSUE TITLE
Publishing Fails Due to Missing metadata.json

### ISSUE THREAD

**Issue by AradSharafi** [umbertoghio/self-hosted-expo-updates-server#15]
Hello 

I'm encountering an error when attempting to publish. The error message received is: "No metadata.json found. Was it included in the zip?" This error results in a BadRequest with a status code of 400. I would like to understand when this error typically occurs and what might be causing it.

I confirm that the zip file is there as well as the metadata.json.

I have consulted with my company's devOps team member, but they were unable to determine the cause of this error.

Can you provide any guidance on how to resolve it?

Thank you in advance!

**Comment by umbertoghio** [comment]
The issue appears to arise form upload.js

![image](https://github.com/umbertoghio/self-hosted-expo-updates-server/assets/25666241/ec465056-c07a-46f4-8a95-81747c47b573)

maybe you can add a console.log of e.message to actually get the reason behind the error?

sorry for the late reply, I am not actively maintaining this project at the moment
