### ISSUE TITLE
issue with docker-entry point  

### ISSUE THREAD

**Issue by pranay213** [umbertoghio/self-hosted-expo-updates-server#20]
updater-api-dev  | exec /docker-entrypoint.sh: no such file or directory                                                                                              
updater-web-dev  | exec /startup-dev.sh: no such file or directory   
![image](https://github.com/user-attachments/assets/6ebe4eb0-d3ce-406c-854c-71b9474df3ac)

**Comment by umbertoghio** [comment]
Can you post your docker compose?

**Comment by pranay213** [comment]
Yes . Please check @umbertoghio 
![image](https://github.com/user-attachments/assets/1bea7826-6d49-4847-aca3-981271bf163e)
![image](https://github.com/user-attachments/assets/1e0e5d8f-ad43-4d30-8052-a1c7c77af573)

**Comment by umbertoghio** [comment]
I don't see any issue that would prevent docker from finding the initial / entry point script.
If you just want to run the system you may use the production docker compose, it will pull the images from the registry and only requires configuration.
On the other hand if you want to develop / extend the platform make sure you run the docker compose from the right folder with --build option

**Comment by sonnv1912** [comment]
i hope it no too late, but seem your problem is file format, on window it is CRLF and linux is LF , you just use docs2unix then everything is fine:

`RUN docs2unix ./startup-dev.sh` 
then
`EXEC [...]`

note: make sure you install docs2unix before

**Comment by Chuazz** [comment]
> i hope it no too late, but seem your problem is file format, on window it is CRLF and linux is LF you just use docs2unix then everything is fine
