### ISSUE TITLE
No expo-signature header specifield 

### ISSUE THREAD

**Issue by sonnv1912** [umbertoghio/self-hosted-expo-updates-server#24]
my clone server: https://github.com/Chuazz/self-host-expo-clone
my app: https://github.com/Chuazz/phone-book-for-old-man

![image](https://github.com/user-attachments/assets/779a6a49-7e50-4d9a-b2f0-ffca316df7da)

**Comment by umbertoghio** [comment]
Nice work!!

**Comment by sonnv1912** [comment]
> Nice work!!

i have research with many site but not found solution for this error

**Comment by umbertoghio** [comment]
Sorry, was In a hurry and missed the error altogether.
so, in you app.json you should point the URL to an instance of the server, localhost will point to the phone itself.
focodeSigningCertificate to use a relative path to the app root, like ./code-signing/certificate.pem, where code-signing is a folder in the root of the mobile app (see example)

**Comment by sonnv1912** [comment]
i have config adb reverse in script and it work, i working on ubutu when i build it location on tmp folder so it dont understand relative path
![image](https://github.com/user-attachments/assets/f3278915-1e34-4ca7-bfb7-301d71c77ec5)

**Comment by umbertoghio** [comment]
"codeSigningCertificate": "../../../../../../home/chuazz/Workspace/freetime/phone-book-for-old-man/code-signing/certificate.pem",
 
 place code-signing/certificate.pem inside the root of your app project and write  "./code-signing/certificate.pem" instead.
 
 You may also try first the example, it should work out of the box

**Comment by sonnv1912** [comment]
i have do it before like this image and it dont understand relative path on ubuntu

![image](https://github.com/user-attachments/assets/f6be7463-b67c-4f30-94c3-39228bdb9039)

**Comment by sonnv1912** [comment]
i have to point it with absolute path

**Comment by umbertoghio** [comment]
the path is already relative, as it starts with ../../../ ...   
seems that you are working with an ejected project, in that case the certificate and metadata needs to be embedded tint the AndroidManifest.xml, look at here for example
https://github.com/umbertoghio/self-hosted-expo-updates-server/blob/master/ExampleEjected/android/app/src/main/AndroidManifest.xml

**Comment by sonnv1912** [comment]
i pretty sure i on an managed project, i do  ../../../... because when on build it create a build folder on /temp/ and it dont understand where ./code-signing in temp builder folder, i have point it back to /home/user/..../code-sigining again

**Comment by sonnv1912** [comment]
i think i will try on window

**Comment by sonnv1912** [comment]
i don't understand but because i ignore *.pem in gitignore then eas build don't copy it into buid folder @@@, thank for your help

**Comment by umbertoghio** [comment]
if you are in managed you must include the pem file, otherwise the build won't copy it

**Comment by sonnv1912** [comment]
i get another error :____, i will create another issue help me if you can :3
