### ISSUE TITLE
Can i use self hosted in local emulator

### ISSUE THREAD

**Issue by sonnv1912** [umbertoghio/self-hosted-expo-updates-server#25]
i have a config to create a self hosted expo with my local emulator and have following error

I don't have enough qualifications to rent a server :((

my app: https://github.com/Chuazz/phone-book-for-old-man
my clone server: https://github.com/Chuazz/self-host-expo-clone

![image](https://github.com/user-attachments/assets/9873604d-8d57-4bb2-96aa-8c54011c0377)

**Comment by umbertoghio** [comment]
Hello, 
never seen this error, are you running a production .apk file on the emulator? it is not supposed to work in development.
About the server URL,  it may need to be in https, so that is another thing to check

**Comment by sonnv1912** [comment]
i also try it on real device, i think my problem is server URL

**Comment by umbertoghio** [comment]
looks like, maybe you can get a domain, point it to your public ip address and then use let's encrypt?

**Comment by sonnv1912** [comment]
i just rent a domain then get same error with #26  @umbertoghio 

like i see, mongo doesn't understand
 environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=myPRODUCTIONPassword # Root/admin password for administration
      - MONGO_INITDB_DATABASE=expo
so it doesn't create these then db become empty for first time
