### ISSUE TITLE
Issue with docker in production

### ISSUE THREAD

**Issue by Dag0n** [umbertoghio/self-hosted-expo-updates-server#26]
```
2024/09/23 07:00PM 30 pid=1 hostname=1a06abc60acb msg=Feathers application started on http://localhost:3000
2024/09/23 07:00PM 30 pid=1 hostname=1a06abc60acb msg=Env: production DB: mongodb://expo@myRegularUserPassw:self_hosted_expo_updates_server_db:27017/expo
2024/09/23 07:00PM 50 pid=1 hostname=1a06abc60acb msg=API - Unhandled Rejection at: Promise 
2024/09/23 07:00PM 50 pid=1 hostname=1a06abc60acb msg=API - Unhandled Rejection at: Promise 
2024/09/23 07:00PM 50 pid=1 hostname=1a06abc60acb msg=API - Unhandled Rejection at: Promise 
2024/09/23 07:00PM 50 pid=1 hostname=1a06abc60acb msg=API - Unhandled Rejection at: Promise 
2024/09/23 07:00PM 50 pid=1 hostname=1a06abc60acb msg=TypeError: Cannot read properties of undefined (reading 'find')
    at Object._find (/home/node/server/node_modules/feathers-mongodb/lib/index.js:123:26)
    at callMethod (/home/node/server/node_modules/@feathersjs/adapter-commons/lib/service.js:13:22)
    at Object.find (/home/node/server/node_modules/@feathersjs/adapter-commons/lib/service.js:63:16)
    at /home/node/server/node_modules/@feathersjs/feathers/lib/hooks/index.js:57:33
    at new Promise (<anonymous>)
    at /home/node/server/node_modules/@feathersjs/feathers/lib/hooks/index.js:54:27
    at async createAdminIfMissing (/home/node/server/src/index.js:18:19)
2024/09/23 07:00PM 50 pid=1 hostname=1a06abc60acb msg=API - Unhandled Rejection at: Promise 
```

Using defaults or amending the docker-compose.yaml I get the above error.

**Comment by umbertoghio** [comment]
Hello, 
seems that the error happens because the db is empty and it is trying to create the admin user, have you managed to go pasti it? maybe a permission issue for the DB

**Comment by sonnv1912** [comment]
same issue with you :v

**Comment by sonnv1912** [comment]
my dockerr-compose.yml

`version: '3.7'
services:
  api:
    image: ghcr.io/umbertoghio/self-hosted-expo-updates-server-api:latest
    container_name: api
    restart: always
    depends_on:
      - database
    volumes:
      - ./updates:/updates # This will store the unzipped updates
      - ./uploads:/uploads # This will hold a copy of the publishes in a zip format
    ports:
      - 3000:3000
    environment:
      - TZ=Europe/Rome # Timezone
      - FEATHERS_AUTH_SECRET=EnterHereYourCustomSecret # Custom secret for feathers authentication and JWT generation
      - MONGO_CONN=mongodb://admin:myPRODUCTIONPassword@database:27017/expo # MongoDB connection string, see mongoinit/init.js
      - ADMIN_PASSWORD=devserver # Password for the admin user
      - UPLOAD_KEY=abc123def456 # Key used in the expo publish custom script
      - NODE_ENV=production
      - PUBLIC_URL=http://157.66.101.16:8080 # Public URL for the server, better if it is a https URL
      - DASBHOARD_THROTTLE_MSEC=5000 # No more than one refresh every 5 seconds fror the dashboard

  self_hosted_expo_updates_server_web:
    image: ghcr.io/umbertoghio/self-hosted-expo-updates-server-web:latest
    container_name: self_hosted_expo_updates_server_web
    restart: always
    depends_on:
      - api
    ports:
      - 8080:80 # Put this behind an https reverse proxy if you want to use it in production
    environment:
      - `API_BASE_URL=http://157.66.101.16:3000` # URL of the API server

  database:
    container_name: database
    image: mongo:4.2.2
    platform: linux/amd64
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      - ./mongoinit:/docker-entrypoint-initdb.d/ # Set database user credenzials in mongoinit/init.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=myPRODUCTIONPassword # Root/admin password for administration
      - MONGO_INITDB_DATABASE=expo
    command: mongod --bind_ip=0.0.0.0 --logpath=/dev/null

volumes:
  mongo_data:`

and my init.js

`/* eslint-disable no-undef */

let db = connect("mongodb://admin:myPRODUCTIONPassword@localhost:27017/admin");

db = db.getSiblingDB("expo");

db.createUser({
  user: "expo",
  pwd: "myRegularUserPassw",
  roles: [
    {
      role: "readWrite",
      db: "expo",
    },
  ],
});`
