### ISSUE TITLE
Failed to download asset with key

### ISSUE THREAD

**Issue by Giasinit** [umbertoghio/self-hosted-expo-updates-server#3]
Buongiorno, mi continua a dare questo errore:
``` 
Failed to download asset with key 0a19d3b69bc6a64f8c76c836a8221e85   
java.io.IOException: File download was successful but base64url-encoded SHA-256 did not match expected; expected: 1WxYOMnI-QnH_02_kA-xEWQfGKsPMIkXnb0Xpbhy6Y0; actual: wcEzwyhl7ySXSsb1jBJVI4Lvho7wNI5RBy4osDBamPw
```
Ogni volta che faccio la build e creo l'APK metto:
` <meta-data android:name="expo.modules.updates.CODE_SIGNING_ALLOW_UNSIGNED_MANIFESTS" android:value="true"/>
` 
Quando invece devo fare un aggiornamento metto:
` <meta-data android:name="expo.modules.updates.CODE_SIGNING_ALLOW_UNSIGNED_MANIFESTS" android:value="false"/>
` 
Come posso risolvere?
Grazie.

**Comment by umbertoghio** [comment]
Ciao , 
ti chiedo scusa ma mi sono completamente perso questa issue.
Hai ancora il problema o hai trovato workaround / soluzione?

**Comment by Giasinit** [comment]
Ciao, ormai avevo lasciato perdere momentaneamente.. riproverò successivamente.
Ti ringrazio!
