### ISSUE TITLE
Bundle upload error: ENOENT: no such file or directory, open '/uploades/...zip'

### ISSUE THREAD

**Issue by SMhdAsadi** [umbertoghio/self-hosted-expo-updates-server#4]
I am trying to upload bundle file to my self-hosted server, following the instructions in the documentation. However, I am encountering the following error message:
```json
{"name":"GeneralError","message":"ENOENT: no such file or directory, open '/uploads/d111b21de6fc6fc7acb64e3cd2d107493f9c3768f85e529461ebc0696c6d0611.zip'","code":500,"className":"general-error","data":{},"errors":{}}
```
I have confirmed that the zip file exists and is located at the specified path on my local machine. I am using the curl command provided in the documentation to upload the file to the server, and I have verified that the server is running and accessible at the specified IP address and port.

I have consulted with my company's devup team member, but they were unable to determine the cause of this error.

Can you provide any insight or guidance on how to resolve this issue?

Thank you for your help!

**Comment by umbertoghio** [comment]
Hello, 
I think the issue may come from [src/services/upload.js ](https://github.com/umbertoghio/self-hosted-expo-updates-server/blob/master/API/src/services/upload.js)

Do you get any more info on the error, i.e. 'Error extracting the archive' or 'upload failed' ?

**Comment by SMhdAsadi** [comment]
We found out that the problem was caused by incorrect permissions on the server, but we fixed it now.
Thanks for your help!
