### ISSUE TITLE
Clarification on how to use privateKey

### ISSUE THREAD

**Issue by SMhdAsadi** [umbertoghio/self-hosted-expo-updates-server#5]
Hello,

I am trying to use this repo for managing updates for my Expo apps. However, I am having some difficulty understanding how to use the privateKey and where to put it on the server.

I have read the README file and followed the instructions provided there, but I still have some questions. Could you please provide some clarification on how to use the privateKey and where to put it on the server?

Thank you for your help.

**Comment by umbertoghio** [comment]
Hello, 
when you generate the key from the admin panel it is saved automatically in the mongoldb and used accordingly.
you need to save the public one (under "App Certificate (download and add this certificate to your app.json):) and either add it to your app.json or on a folder, you can check the two example apps in the code-signing folder.

**Comment by SMhdAsadi** [comment]
Thanks!
