### ISSUE TITLE
[question] Is this Expo classic updates?

### ISSUE THREAD

**Issue by timothymiller** [umbertoghio/self-hosted-expo-updates-server#6]
Thanks for the hard work putting this together!

Expo's update API changed recently. Is this update server an implementation of expo classic updates? Or the newer flavor?

**Comment by umbertoghio** [comment]
Hi Timothy, 
I'm not sure, I know it works with Expo 48 with the compatible update library, so it is compatible with EAS-update 
(is that what you mean?)

**Comment by SMhdAsadi** [comment]
This is not for old classic updates. It works well with new Expo update.
