### ISSUE TITLE
Update Required for Documentation Regarding Expo SDK 49

### ISSUE THREAD

**Issue by SMhdAsadi** [umbertoghio/self-hosted-expo-updates-server#7]
Following the recent update to Expo SDK 49, it appears that the instructions outlined in [this section](https://github.com/umbertoghio/self-hosted-expo-updates-server#build-a-new-app) are no longer necessary. 

The `expo publish` command, previously required, is now redundant. Expo now automatically generates a new embedded update with each build. 

Also, users can now start the development server using the following command:

```sh
npx expo start --private-key-path (path to the private key)
```

So modifications to AndroidManifest and Expo.plist, as previously instructed, are no longer required. 

This issue is raised to suggest an update to the documentation to reflect these changes and provide accurate instructions for users of Expo SDK 49.

P.S. I don't know if these changes are applicable to Expo SDK < 49.

**Comment by umbertoghio** [comment]
Hi Seyed, 
thank you for pointing out this, I'm about to update an app from expo 48 to expo 49 and I'll definitely give it a try and update the documentation in the next days.
If you are using this project and finds some area that needs improvement don't hesitate to let me know or send PRs!

**Comment by umbertoghio** [comment]
Thanks @SMhdAsadi , I've updated the documentation
