### ISSUE TITLE
Error 500 Internal Server Error When Sending a New Update

### ISSUE THREAD

**Issue by SMhdAsadi** [umbertoghio/self-hosted-expo-updates-server#8]
### Description:
I would like to express my gratitude for your contributions to this project.

I've successfully tested the development Docker environment, and it functioned perfectly. However, upon deploying the production Docker on our server, I encountered an error. The web interface operates as expected; however, when attempting to send a new update to the server using the script your provided, I receive the following error message after curl command:

```html
<html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
</body>
</html>
```

I have shared this issue with our DevOps team, but thus far, they have been unable to identify the root cause. They mention that there are no relevant logs on the server side.

### Request for Assistance:
I am seeking insights into the potential reasons behind this error message. Any assistance or guidance you can provide would be greatly appreciated as we work to resolve this issue. Thank you in advance for your help.

**Comment by umbertoghio** [comment]
Hello, 
sorry but I completely missed this issue!
Have you managed to resolve it? 
Otherwise you can also drop me an email at "umberto" then the at and then "ghio.io"
Closing this issue for now

**Comment by SMhdAsadi** [comment]
Hi.
Yeah I resolved this issue. I don't know what was the exact cause of that since I don't know Docker very well. But it is fixed.
Thanks for your support :)
