### ISSUE TITLE
[Feature Request] Add support for ARM64

### ISSUE THREAD

**Issue by JustJoostNL** [umbertoghio/self-hosted-expo-updates-server#9]
Hey,

The library currently doesn't work on ARM64. Is it possible to add support for that?

**Comment by umbertoghio** [comment]
> Hey,
> 
> 
> 
> The library currently doesn't work on ARM64. Is it possible to add support for that?

Hi, I will try to build an arm64 docker image, will leave this issue open until then

**Comment by JustJoostNL** [comment]
Thanks!

**Comment by JustJoostNL** [comment]
@umbertoghio any updates on this?

**Comment by umbertoghio** [comment]
Hi, sorry for the late reply, I was trying to figure out a way to automate multi-architecture build, but was stuck on another project. 
II've just released 
ghcr.io/umbertoghio/self-hosted-expo-updates-server-api:arm64
ghcr.io/umbertoghio/self-hosted-expo-updates-server-web:arm64

and will keep them up to date with future changes.
Have a great day!

**Comment by JustJoostNL** [comment]
Thanks!

**Comment by manhtruongwang** [comment]
I just tried to use arm64 image but when I curl http://localhost:8080
I got - curl: (56) Recv failure: Connection reset by peer

This happens on the web version only

Update - the port for arm64 is port 80 not 8080 exposed port 8080:80 work
